name: diet_application
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0"

dependencies:
  bloc_test: ^9.0.3
  equatable: ^2.0.3
  firebase_auth: ^4.19.0
  firebase_auth_mocks: ^0.13.0
  firebase_core: ^2.28.0
  firebase_ui_auth: ^1.13.1
  firebase_ui_oauth_google: ^1.3.1
  flow_builder: ^0.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_facebook_auth: ^6.1.1
  flutter_localizations:
    sdk: flutter
  font_awesome_flutter: ^10.1.0
  google_sign_in: ^6.2.1
  test: 1.24.9
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.2

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/icons/app_logo.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/images/icons/
