import 'package:diet_application/src/SideNav/CustomScaffold/custom_scaffold.dart';
import 'package:diet_application/src/screens/Menu/menu_list.dart';
import 'package:flutter/material.dart';

class Menu extends StatefulWidget {
  const Menu({Key? key}) : super(key: key);
  static const routeName = '/menu';

  @override
  State<Menu> createState() => _MenuState();
}

class _MenuState extends State<Menu> {
  @override
  Widget build(BuildContext context) {
    return CustomScaffold(
      title: const Text("Today's Menu"),
      child: Column(children: [
        Image.asset("assets/images/MenuHeader.png"),
        const SizedBox(height: 10),
        MenuListTile(
            title: "Proteins",
            units: "gm",
          img: "proteins.jpg",
            items: const [
              "Milk",
              "Eggs",
              "Chicken",
              "beef",
              "lamb",
              "veal",
              "pork",
              "kangaroo",
              "turkey",
              "duck",
              "emu",
              "goose",
              "bush birds",
              "fish",
              "prawns",
              "crab",
              "lobster",
              "mussels",
              "oysters",
              "scallops",
              "clams",
              "yoghurt",
              "cottage cheese",
              "almonds",
              "pine nuts",
              "walnuts",
              "macadamias",
              "hazelnuts",
              "cashews",
              "pumpkin seeds",
            ],
        ),
        MenuListTile(
          title: "Carbohydrates",
          units: "kcal",
          img: "Carbohydrate.jpeg",
          items: const [
            "Grains",
            "bread",
            "noodles",
            "pasta",
            "crackers",
            "cereals",
            "rice",
            "milk",
            "yoghurt",
            "Pulses",
            "apples",
            "bananas",
            "berries",
            "mangoes",
            "melons",
            "oranges",
            "dried beans",
            "lentils",
            "peas",
            "cakes",
            "cookies",
            "candy",
            "desserts",
            "Juices",
            "sodas",
            "fruit drinks",
            "sports drinks",
            "energy drinks",
            "potatoes",
            "corn"
          ],
        ),
        MenuListTile(
          title: "Vitamins",
          units: "gm",
          img: "vitamins.jpg",
          items: const [
            "Fruits",
            "Vegetables",
            "Salads",
            "Broccoli",
            "cauliflower",
            "Brussels sprouts",
            "Leafy greens",
            "chard",
            "cabbage",
            "romaine",
            "bok choy",
            "spinach",
            "kale",
            "Squash",
            "carrots",
            "sweet potatoes",
            "turnips",
            "pumpkin",
            "Snap peas",
            "green beans",
            "bell peppers",
            "asparagus",
            "Apples",
            "plums",
            "mangos",
            "papaya",
            "pineapple",
            "bananas",
            "Blueberries",
            "strawberries"
          ],
        ),
        MenuListTile(
          title: "Potassium",
          units: "gm",
          img: "Potassium.jpg",
          items: const [
            "Dried Fruits",
            "Spinach",
            "Brocoli"
                "Dried fruits",
            "raisins",
            "apricots",
            "Beans",
            "lentils",
            "Potatoes",
            "Winter squash",
            "Spinach",
            "broccoli",
            "Beet greens",
            "Avocado",
            "Bananas",
            "Cantaloupe",
            "Oranges",
            "orange juice",
            "Coconut water",
            "Tomatoes",
            "plant milks",
            "Yogurt",
            "Cashews",
            "almonds",
            "Chicken",
            "Salmon",
            "Tuna",
            "Halibut",
            "Cod",
            "Trout",
            "Rockfish",
          ],
        )
      ]),
    );
  }
}
