// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCz5X9hWwLfd8-j34PIPA-geWqy5afBXPI',
    appId: '1:559371234950:web:b6d0405066ef4002fc2b07',
    messagingSenderId: '559371234950',
    projectId: 'seal-the-meal',
    authDomain: 'seal-the-meal.firebaseapp.com',
    storageBucket: 'seal-the-meal.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCx_sGquMDSeD1N_oZ6f6k3Rhh8aF60_-A',
    appId: '1:559371234950:android:9c87866044520a44fc2b07',
    messagingSenderId: '559371234950',
    projectId: 'seal-the-meal',
    storageBucket: 'seal-the-meal.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnUR_NoyRPGP-LhjJOY29U3k3k-nX0zvQ',
    appId: '1:559371234950:ios:2559763818d48ed6fc2b07',
    messagingSenderId: '559371234950',
    projectId: 'seal-the-meal',
    storageBucket: 'seal-the-meal.appspot.com',
    iosClientId:
        '559371234950-l4scolch55qtmsjh5885o4229p445fvp.apps.googleusercontent.com',
    iosBundleId: 'com.example.dietApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnUR_NoyRPGP-LhjJOY29U3k3k-nX0zvQ',
    appId: '1:559371234950:ios:2559763818d48ed6fc2b07',
    messagingSenderId: '559371234950',
    projectId: 'seal-the-meal',
    storageBucket: 'seal-the-meal.appspot.com',
    iosClientId:
        '559371234950-l4scolch55qtmsjh5885o4229p445fvp.apps.googleusercontent.com',
    iosBundleId: 'com.example.dietApplication',
  );
}
