// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnMOpylARAVwSc8iIsAIaz4edMuA4P_0Q',
    appId: '1:890699934482:web:692b042bc66c4b647d61cb',
    messagingSenderId: '890699934482',
    projectId: 'diet-application-acf40',
    authDomain: 'diet-application-acf40.firebaseapp.com',
    storageBucket: 'diet-application-acf40.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQyDqXXvgcrhFMMS-fam_xxRqS9BXzymo',
    appId: '1:890699934482:android:c6b78ebdd44095fd7d61cb',
    messagingSenderId: '890699934482',
    projectId: 'diet-application-acf40',
    storageBucket: 'diet-application-acf40.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1cWWXnG_48wHfbD5X9GkJOu3AiXu5H00',
    appId: '1:890699934482:ios:686fd6a3b8e758b47d61cb',
    messagingSenderId: '890699934482',
    projectId: 'diet-application-acf40',
    storageBucket: 'diet-application-acf40.appspot.com',
    androidClientId: '890699934482-qtbj81diamrevnuch1ficas8r9h8v309.apps.googleusercontent.com',
    iosClientId: '890699934482-invg72qd9eu7kdbuc2nq720b4njq53qj.apps.googleusercontent.com',
    iosBundleId: 'com.example.dietApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1cWWXnG_48wHfbD5X9GkJOu3AiXu5H00',
    appId: '1:890699934482:ios:686fd6a3b8e758b47d61cb',
    messagingSenderId: '890699934482',
    projectId: 'diet-application-acf40',
    storageBucket: 'diet-application-acf40.appspot.com',
    androidClientId: '890699934482-qtbj81diamrevnuch1ficas8r9h8v309.apps.googleusercontent.com',
    iosClientId: '890699934482-invg72qd9eu7kdbuc2nq720b4njq53qj.apps.googleusercontent.com',
    iosBundleId: 'com.example.dietApplication',
  );
}
